steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bekasi-keren/absensi', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bekasi-keren/absensi']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'absensi', '--image', 'gcr.io/bekasi-keren/absensi', '--platform', 'managed', '--region', 'us-central1']

images:
  - 'gcr.io/bekasi-keren/absensi'

options:
  logging: CLOUD_LOGGING_ONLY
